### ISSUE TITLE
Vagrent up fails: Apparently puppet is not installed or not on the path

### ISSUE THREAD

**Issue by ks32849** [AnthonyNystrom/python-dev-bootstrap#11]
Here's what I get upon vagrant up:
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'PythonDevBootstrap_13_10'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: python-dev-bootstrap_default_1421932028819_79388
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Error: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /share => G:/virtualbox/share
    default: /vagrant => G:/python-dev-bootstrap
    default: /tmp/vagrant-puppet-1/manifests => G:/python-dev-bootstrap/manifests
    default: /tmp/vagrant-puppet-1/modules-0 => G:/python-dev-bootstrap/modules
==> default: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.

KS32849@DE05236W /g/python-dev-bootstrap (master)

BTW I had to create an (empty) modules directory, since I got an error complaining it was not available.

**Comment by joequery** [comment]
Why is this closed? Was there a resolution?

**Comment by doctordesh** [comment]
I got both of these issues too. Had to create empty modules directory and puppet doesn't appears in my path. A solution would be nice!

And of course, puppet is installed. Installed it with homebrew so it should work.
